### ISSUE TITLE
How to Register a Phone Number

### ISSUE THREAD

**Issue by xrimpy** [ignacio-chiazzo/ruby_whatsapp_sdk#106]
According to the documentation 

`phone_numbers_api.register_number(phone_number_id, pin)`

Will register a Phone Number on the account.

How do I generate the PIN on the phone to be registered?

**Comment by ignacio-chiazzo** [comment]
Could you elaborate more on what do you mean by PIN?

**Comment by ignacio-chiazzo** [comment]
It's the PIN you used on the phone. You can also update it if you don't remember its value https://developers.facebook.com/docs/whatsapp/cloud-api/reference/two-step-verification#updating-verification-code
