### ISSUE TITLE
Use major version compatible dependencies

### ISSUE THREAD

**Issue by nbluis** [ignacio-chiazzo/ruby_whatsapp_sdk#107]
I believe this is a little detail but it would be better if the dependencies defined in the gemspec did not fix minor or patch versions, otherwise projects that include this gem will never be able to update these dependencies without a release even if they are compatible (semver)

**Additional context**
An example of this is now occurring with Faraday.

Gemspec
```
spec.add_dependency("faraday", "~> 2.7.10")
```

The last Faraday version is v2.7.11 and theres no breaking changes.

**Comment by ignacio-chiazzo** [comment]
Hey! That's a very good call. 

I'm okay with doing the same for the other gems (e.g. `faraday-multipart`). 

Do you want to open a PR? Thanks!
