### ISSUE TITLE
Regarding refreshing the access token

### ISSUE THREAD

**Issue by ahmadabdelhalim** [ignacio-chiazzo/ruby_whatsapp_sdk#110]
Hello,

So it seems the access token provided by Facebook is temporary and it needs to be refreshed each day I think, is that implemented inside the gem, or do I need to handle that from my end? 

Thank you,

**Comment by ignacio-chiazzo** [comment]
You have two options: 
1) You can generate a permanent token and have mechanisms to refresh the token.
2) Refresh the token daily.

**Comment by ahmadabdelhalim** [comment]
Got it. Thank you!
