### ISSUE TITLE
How to send messages Production Environment?

### ISSUE THREAD

**Issue by ademir10** [ignacio-chiazzo/ruby_whatsapp_sdk#111]
**Describe the bug**
After to finish all configuration and added the new phone number, when i try to send a message using the Gem, I receive the message "message sent" but the recipient dont receive any message.

**To Reproduce**
the Code below:
def send_whatsapp_message
  @config = Config.first
  require 'whatsapp_sdk'

  #variables
  access_token = @config.access_token_whats
  business_id = @config.business_id_whats
  sender_id = @config.sender_id_whats
  recipient_number = params[:numero_whatsapp]

  client = WhatsappSdk::Api::Client.new(access_token) # replace this with a valid access token
  messages_api = WhatsappSdk::Api::Messages.new(client)

  message_sent = messages_api.send_text(sender_id: sender_id.to_i, recipient_number: recipient_number.to_i, message: params[:mensagem].to_s)
  print_message_sent(message_sent)
  redirect_back(fallback_location: root_path)
end

def print_message_sent(message_response)
  if message_response.ok?
    sweetalert_success("Mensagem enviada com sucesso para: #{message_response.data.contacts.first.input}", 'Sucesso!', persistent: 'Ok')
    puts "Message sent to: #{message_response.data.inspect}"
  else
    sweetalert_success("Ocorreu um erro:  #{message_response.error&.to_s}", 'Erro:', persistent: 'Ok')
  end
end

THIS IS MY RESPONSE:
Message sent to: #<WhatsappSdk::Api::Responses::MessageDataResponse:0x000000010667d728 @contacts=[#<WhatsappSdk::Resource::ContactResponse:0x000000010667d570 @input="5511991078572", @wa_id="5511991078572">], @messages=[#<WhatsappSdk::Resource::Message:0x000000010667d368 @id="wamid.HBgNNTUxMTk5MTA3ODU3MhUCABEYEjBFQkI2OEYyNTdBMTBDRUY1NwA=">], @raw_data_response={"messaging_product"=>"whatsapp", "contacts"=>[{"input"=>"5511991078572", "wa_id"=>"5511991078572"}], "messages"=>[{"id"=>"wamid.HBgNNTUxMTk5MTA3ODU3MhUCABEYEjBFQkI2OEYyNTdBMTBDRUY1NwA="}]}>

**Expected behavior**
The recipient receive the message.

If you look to my configs at images attached you can see that everything is configured, (I guess)
There is something else more to do?
thanks!

**Additional context**
Add any other context about the problem here
<img width="843" alt="Captura de Tela 2023-11-28 às 16 36 53" src="https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/assets/2720896/d67783d7-9c33-4eb6-ab44-33e465194181">
<img width="1021" alt="Captura de Tela 2023-11-28 às 16 37 18" src="https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/assets/2720896/c180733c-1d3c-4329-bcda-dad046ca096a">
<img width="1722" alt="Captura de Tela 2023-11-28 às 16 38 39" src="https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/assets/2720896/669d0978-208d-4631-a235-25412d1e9b6b">
.

**Comment by ademir10** [comment]
Hi! thanks for your help.
Yes! when i try to send using the Meta API everything is working as expected, but when i try to do the same using the Gem, ia receive the message sent, but i dont receive the message in my device.

**Comment by ademir10** [comment]
Only after to do it started to receive the messages:
"Try also replying a message to the number you are registered on your Whatsapp."

Do you know if i need to do something else more?

what is this?:
phone_numbers_api = WhatsappSdk::Api::PhoneNumbers.new

**Comment by ademir10** [comment]
What about this step 6?
I don't did it...

has something to do with it to make the recipient receive the message?

<img width="590" alt="Captura de Tela 2023-11-28 às 17 30 03" src="https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/assets/2720896/3535d6b0-d08d-4648-b6cf-2878b87cd013">

**Comment by ademir10** [comment]
Finally i found the problem @ignacio-chiazzo !
Just to help more people with the same error:

1 - If you try to send a text message directly without to use a message template created and approved in your Meta control panel, you can't start a chat with other people, but if you receive a message before, it's possible to send a message.

- If you send a message for the first time to recipient, you need to create a MESSAGE TEMPLATE and send to review
- Only after to approved your message template you gonna be able to make recipients receive it.
Hope it help you, guys.
God bless you!

**Comment by ignacio-chiazzo** [comment]
I have added your suggestion to the README. Thank you.
