### ISSUE TITLE
Sending a template with a dynamic URL 

### ISSUE THREAD

**Issue by ahmadabdelhalim** [ignacio-chiazzo/ruby_whatsapp_sdk#115]
I created a template for WhatsApp and the template includes a button that has a dynamic URL, I'm trying to use that template to send a message, but I'm getting an error, I'm not sure what am I doing wrong here. I attached images with my code and the error I'm getting.

![CleanShot 2023-12-06 at 13 49 39](https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/assets/36769378/2fabfc61-4b53-49d3-b27b-07650df4f519)
![CleanShot 2023-12-06 at 13 53 41](https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/assets/36769378/a7f3023f-9807-48f5-968d-bc9a178fb289)

Thank you,

**Comment by ahmadabdelhalim** [comment]
I managed to fix it after some investigation by doing the following
![CleanShot 2023-12-07 at 15 00 33](https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/assets/36769378/faa85021-3ff5-4618-a1ca-6385c160371b)

**Comment by ignacio-chiazzo** [comment]
Hi, thanks for reporting. 

What was the fix? Was adding index: 0? 

This could be something we can document AND/OR add an error if the developer doesn't pass the parameters correctly.
