### ISSUE TITLE
Add the ability to set the API version during configuration

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/ruby_whatsapp_sdk#117]
Currently, the Whatsapp API version is [hardcoded here](https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/pull/116/files#diff-a390dc35ca2712fcb4ecb4c6a439ef44bfd3d01267ee9b4ca1e549f1298b2fceR9). We should expose a way for apps to set up the API version during initialization. 

For example, we could provide a config method `api_version` which sets the version for all API requests. 

### Hints

The configuration lives in [`configuration.rb`](https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/main/lib/whatsapp_sdk/configuration.rb). We could accept an `api_version` argument which is used across the API. 

If the argument isn't passed, we'd use the hardcoded version.

**Comment by paulomcnally** [comment]
What do you think about creating the ruby_whatsapp_sdk_rails gem where https://rubygems.org/gems/railties can be used to create an initializer to set this value?

My suggestion is for projects where Ruby on Rails is used.

**Comment by paulomcnally** [comment]
This is an basic example -> https://github.com/paulomcnally/ruby_whatsapp_sdk_rails (This repository is an example, I do not plan to release the gem)

**Comment by ignacio-chiazzo** [comment]
I would like to update the library so that it is framework agnostic (not rails required). I think the setup is easy enough that devs can include it on their repo. 

What's the goal of the gem?

**Comment by paulomcnally** [comment]
I have seen that it is common practice to create a gem for use in rails where it gives you the benefit of generators, initializer logic through rails, etc.

It would definitely be enough to implement it in the library as you do for access_token.

**Comment by conr** [comment]
Hey there @ignacio-chiazzo 👋🏻 

Can you assign this issue to me?

I would love to work on it. Cheers!

**Comment by ignacio-chiazzo** [comment]
Sure! Thanks

**Comment by conr** [comment]
I think you accidentally assigned it to yourself 😄

**Comment by ignacio-chiazzo** [comment]
Oh haha sorry, fixed!

**Comment by conr** [comment]
Shall we close this issue now? 🙂
