### ISSUE TITLE
`rails zeitwerk:check` crashes

### ISSUE THREAD

**Issue by mgruner** [ignacio-chiazzo/ruby_whatsapp_sdk#132]
**Describe the bug**
We use this gem in our Rails application, thank you so much for providing it! 

While the regular rails stack still seems to work fine, the `zeitwerk:check` rake task that we use for linting in CI fails now:

```
$ rails r 'pp true'
true

$ rails zeitwerk:check
Hold on, I am eager loading the application.
rails aborted!
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - config/api_versions.yml (Errno::ENOENT)

Tasks: TOP => zeitwerk:check
(See full trace by running task with --trace)
```

**To Reproduce**
1. Run `rails zeitwerk:check` in your rails app.

**Expected behavior**
No error should occur.

**Additional context**

It seems that the recent changes from #126 introduced a regression. 

Could it be an alternative to switch from loading a yaml file to preparing the list directly in a ruby file?

**Comment by mgruner** [comment]
I can also reproduce it when trying to create an instance of our WhatsApp client wrapper object:

```
rails r 'pp Whatsapp::Client.new(access_token: "123")'
/Users/mg/.rvm/gems/ruby-3.2.3/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/yaml.rb:234:in `realpath': No such file or directory @ rb_check_realpath_internal - config/api_versions.yml (Errno::ENOENT)
```

**Comment by ignacio-chiazzo** [comment]
0.12.1 contains the fix. THanks @mgruner for contributing

**Comment by mgruner** [comment]
Thank you @ignacio-chiazzo.
