### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by kalicki** [ignacio-chiazzo/ruby_whatsapp_sdk#139]
Hi, from what I saw the SDK doesn't support group management, I'll put some things here to understand how the groups API works
- Create Group
- Update group info
- Send message in group
- Remove group participant

**Comment by ignacio-chiazzo** [comment]
Hey, Whatsapp Cloud API does not provide a Group management API.

**Comment by kalicki** [comment]
It seems so, only in Business API =/
