### ISSUE TITLE
Zeitwerk::NameError

### ISSUE THREAD

**Issue by ademir10** [ignacio-chiazzo/ruby_whatsapp_sdk#44]
**Describe the bug**
After we try to use the gem in our production Environment  (Linux Server) we faced with a error:
**Zeitwerk::NameError**
It just happens in Linux but when we test in a MacOS everything is working fine.

**To Reproduce**
1. Ruby version: 2.7.1
2. Rails 6.0.4.4
3. ruby_whatsapp_sdk-0.5.1 

**Expected behavior**
Start the server and send whatsapp messages through the gem

**Additional context**
Nothing

**Comment by ignacio-chiazzo** [comment]
Hey, thanks for reporting!

I just shipped a fix https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/pull/45 let me know if you're still having the issue.

**Comment by ignacio-chiazzo** [comment]
The latest version `0.6.0` fixed the error. Please let me know if you still have the issue.

Thanks for reporting.
