### ISSUE TITLE
Add send reaction message

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/ruby_whatsapp_sdk#51]
Cloud API just released a reaction API 

https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages#reaction-messages

TODO
- [ ] Add a new function to the `messages.rb` file similar to any other type of message
https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/abd53efce563e19349cef8785dea0c43f6e71a85/lib/whatsapp_sdk/api/messages.rb#L64-L94

The type should be reaction and the hptt method is post.

- [ ] Add test in the message https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/main/test/whatsapp/api/messages_test.rb

**Comment by Sachin1939** [comment]
Hey @ignacio-chiazzo , could you please assign this issue to me as this would help me to start my open source contribution journey.
Thanks!

**Comment by ignacio-chiazzo** [comment]
Thanks @sanchezpaco! The `send_reaction` was released as part of `0.7.0`.
