### ISSUE TITLE
Add Business API

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/ruby_whatsapp_sdk#52]
Add Business profile API https://developers.facebook.com/docs/whatsapp/cloud-api/reference/business-profiles

TODO:
Add the new business profile API
- [x] Create a file `business_profile.rb` in `lib/whatsapp_sdk/api/business_profile.rb`, similar to https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/main/lib/whatsapp_sdk/api/phone_numbers.rb.
- [x] Add a test file.
- [x] Add get method
- [x] Add update method

Documentation: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/business-profiles

**Comment by sahilbansal17** [comment]
Hi @ignacio-chiazzo Can I work on this?

**Comment by ignacio-chiazzo** [comment]
Hey @sahilbansal17 sure
