### ISSUE TITLE
Ho i can use sessions?

### ISSUE THREAD

**Issue by abdugaliyev** [ignacio-chiazzo/ruby_whatsapp_sdk#54]
Hi, can you help me? I need to track users messages and answers, how i can use session? For example rack?
**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by ignacio-chiazzo** [comment]
Hey! sure

You can use Webhooks to parse messages by using the read operation. 

[Take a look at this repository.](https://github.com/ignacio-chiazzo/ruby_on_rails_whatsapp_example). It's a Rails application example that allows sending messages and listening to Webhooks. Particularly, I set up a controller and set up webhooks in the Facebook dashboard to ping that endpoint whenever an event happens (i.e. a message is received).

**Comment by abdugaliyev** [comment]
> Hey! sure
> 
> You can use Webhooks to parse messages by using the read operation.
> 
> [Take a look at this repository.](https://github.com/ignacio-chiazzo/ruby_on_rails_whatsapp_example). It's a Rails application example that allows sending messages and listening to Webhooks. Particularly, [I set up a controller](https://github.com/ignacio-chiazzo/ruby_on_rails_whatsapp_example/blob/main/app/controllers/whatsapp_webhooks_controller.rb#L12) and set up webhooks in the Facebook dashboard to ping that endpoint whenever an event happens (i.e. a message is received).

But its doesn't work, i use Sinatrarb, then enable sessions, after receiving messages, sessions not present in response

**Comment by ignacio-chiazzo** [comment]
Do you have a repository I can look ? Also, feel free to message me on [twitter](https://twitter.com/IgnacioChiazzo) if it's easier to chat.

**Comment by abdugaliyev** [comment]
> Do you have a repository I can look ? Also, feel free to message me on [twitter](https://twitter.com/IgnacioChiazzo) if it's easier to chat.

Yes, i create sample app,

git@github.com:abdugaliyev/sinatratestapp.git

https://github.com/abdugaliyev/sinatratestapp

Please check read me

**Comment by ignacio-chiazzo** [comment]
Hey! did you solve the problem? 

Feel free to reopen the issue if you still face it.
