### ISSUE TITLE
Include websites to the business api

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/ruby_whatsapp_sdk#55]
This PR introduced the business API. It's missing websites https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/pull/53#pullrequestreview-1143344949. 

TODO:
- [x] Add websites to the business profile data response
- [x] Add tests for receiving business profiles.

https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/pull/53

**Comment by sahilbansal17** [comment]
I have created a PR for the same: #56

Please review @ignacio-chiazzo. Thanks.
