### ISSUE TITLE
Can we send message with multiple phone numbers?

### ISSUE THREAD

**Issue by datnguyen199** [ignacio-chiazzo/ruby_whatsapp_sdk#63]
Hi, I have following issue, pls take a look

Base on my research, Whatsapp let us add maximum 2 phone numbers to an Whatsapp business account. 
So now if I have an system with multiple users register as a business (ex: user1 is owner of flower company, user2 is owner of food company...) and I want to integrate Whatsapp API (send messages, reply, get messages...) for each their customers. The whole system with a lot of 'business users' (user1, user2...) will be use same phone numbers as registered to Whatsapp developer app before when they send messages to their customers, right ? So when customer receive messages, they will see same name of business with same phone number. 

Can we use each phone number of users when they registered to system when send messages through Whatsapp ?

**Comment by ignacio-chiazzo** [comment]
Hey!

> Whatsapp let us add maximum 2 phone numbers to an Whatsapp business account.

Where does it say that? I found this:

`There is no limit to the amount of business phone numbers that can be onboarded to the Cloud API.` https://developers.facebook.com/docs/whatsapp/cloud-api/get-started-for-bsps

**Comment by datnguyen199** [comment]
Hi @ignacio-chiazzo tks for your response, yes, I saw we can send multiple request with different sender numbers, but can we add sender by api or need add manual first then verify after that?

**Comment by ignacio-chiazzo** [comment]
Oh I see! thanks for letting me know.

I noticed that whatsapp released a new API `register`. I created a ticket for that https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/issues/64. 

Note that after it's implemented, the user must validate the register through 2FA with a SMS.

**Comment by datnguyen199** [comment]
@ignacio-chiazzo yes, that great !

**Comment by ignacio-chiazzo** [comment]
Hey the API has been released. I will close this issue. Thanks!
