### ISSUE TITLE
Implement Register API

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/ruby_whatsapp_sdk#64]
Cloud API released `register` API. 

Steps to implement it:
- [x] Create the methods `register` and `deregister` in the file lib/whatsapp_sdk/api/phone_numbers.rb similar to the other two methods (you need to use http `POST`).
- [x] Add a test file.

[See documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/registration).

**Comment by andresyebra** [comment]
Could I take this?

**Comment by ignacio-chiazzo** [comment]
Sure! @andresyebra. This PR is very similar https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/pull/58/files

**Comment by andresyebra** [comment]
@ignacio-chiazzo PR(https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/pull/65) is still in progress.

**Comment by ignacio-chiazzo** [comment]
The registered API is in version 0.7.1. Thanks for contributing!
<img width="460" alt="Screen Shot 2023-02-11 at 10 47 19 AM" src="https://user-images.githubusercontent.com/11672878/218267486-4dcc1d28-48c8-4c0d-ab17-1c57abc7d1e6.png">
