### ISSUE TITLE
Send Message as a Reply

### ISSUE THREAD

**Issue by alienware** [ignacio-chiazzo/ruby_whatsapp_sdk#76]
**Is your feature request related to a problem? Please describe.**
I'm working on a use-case that involves replying to users' messages with context, i.e., against an existing conversation, shown as below.
<img width="446" alt="WA Reply" src="https://user-images.githubusercontent.com/2356208/220635673-bf9d449d-2889-428e-b2f3-6b9bada5411e.png">

**Additional context**
[Documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages/#replies)
Enabling this would require to pass `context` object with the request params, which will have the `message_id` for the user message. Replies seem to be supported for `text`, `audio`, `document`, `video`, `location`, `sticker` and `contact`.

Please let me know how I can help out here in case you wish to incorporate the support in this helpful library.

**Comment by ignacio-chiazzo** [comment]
Thanks @alienware, for the feature! 

I cut a release and added your feature to the v.0.7.3 version https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/pull/78
