### ISSUE TITLE
Implement interactive message API.

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/ruby_whatsapp_sdk#8]
The `messages_api` allows users to send interactive messages. 

We need to implement the functions defined in `messages.rb` 

https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/5cf41178f74ffaf7f69a5832af4f5cc517466f17/lib/whatsapp/api/messages.rb#L181-L190

Read the [FB documentation here](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#contacts-object).

**Comment by alienware** [comment]
Hey again @ignacio-chiazzo, I would like to go ahead with adding integration for sending interactive list messages/sections from the TODOs of #79 

I had a question regarding the implementation, is it okay to rename the newly added, but unreleased interactive API `send_interactive_reply_buttons` to `send_interactive_message`? As per the [documentation](https://developers.facebook.com/docs/whatsapp/guides/interactive-messages/) and our support for `Interactive` resource, we should use the same for all `send_interactive_button`, `send_interactive_reply_buttons`, `send_interactive_section` etc. Please let me know what your alternative would be.

**Comment by ignacio-chiazzo** [comment]
> is it okay to rename the newly added, but unreleased interactive API send_interactive_reply_buttons to send_interactive_message? 

Yes, I agree that's the right move. Adding breaking changes to that method is fine since it isn't released.

**Comment by ignacio-chiazzo** [comment]
Thanks @alienware! the version 0.8.0 was just released and contains interactive messages!
![IMG_19E1E41CDB15-1](https://user-images.githubusercontent.com/11672878/226069925-8b66e04a-7ae1-4876-8c2f-12a4774b9863.jpeg)
