### ISSUE TITLE
Add location header to templates

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/ruby_whatsapp_sdk#85]
The API just released, adding the location to the template via headers:

API responses to [template creation and editing requests](https://developers.facebook.com/docs/whatsapp/business-management-api/message-templates) now include the template's status and category.

**Comment by Aaryanpal** [comment]
Let me in @ignacio-chiazzo

**Comment by ignacio-chiazzo** [comment]
@Aaryanpal have you have a chance to look at it?

**Comment by piscespieces** [comment]
Hey @ignacio-chiazzo 

I see this issue has been stale for quite some time, and I'd like to take a peek. I'm still learning the ropes of the API and this codebase. So, to clarify a bit on the ask 

Is this the approach you'd like to have when adding location headers when sending templates?

Let me know if I'm on the right track and/or missing something

```rb
location = WhatsappSdk::Resource::Location.new(
  latitude: 25.779510,
  longitude: -80.338631,
  name: "My Miami Store",
  address: "820 NW 87th Ave, Miami, FL"
)
location_parameter = WhatsappSdk::Resource::ParameterObject.new(type: "location", location: location)
location_component = WhatsappSdk::Resource::Component.new(
  type: WhatsappSdk::Resource::Component::Type::Header,
  parameters: [location_parameter]
)

messages_api.send_template(
  sender_id: 123,
  recipient_number: 123,
  name: "location_test",
  language: "en_US",
  components: [location_component]
)
```

**Comment by piscespieces** [comment]
Yeah, when _creating_ a template with a location header you must pass the `"format": "location"

However, you don't have to when _sending_ a template—I'll open a PR, and we can continue the discussion there.

[Here's the _sending_ a template with location docs for reference](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates/#example-request)
