### ISSUE TITLE
Support Image/webp

### ISSUE THREAD

**Issue by renatovico** [ignacio-chiazzo/ruby_whatsapp_sdk#94]
**Describe the bug**
When receive a image/webp (sticker eg)  the download medias doesn't work

**To Reproduce**
1.  Send a sticker image
2. Try download :)

**Expected behavior**
Download happened

**Additional context**

I Made a ugly monkey patch 

```
WhatsappSdk::Resource::MediaTypes::IMAGE_TYPES = WhatsappSdk::Resource::MediaTypes::IMAGE_TYPES.dup
WhatsappSdk::Resource::MediaTypes::IMAGE_TYPES.push("image/webp")
WhatsappSdk::Resource::MediaTypes::IMAGE_TYPES.freeze


WhatsappSdk::Resource::MediaTypes::SUPPORTED_MEDIA_TYPES = WhatsappSdk::Resource::MediaTypes::SUPPORTED_MEDIA_TYPES.dup
WhatsappSdk::Resource::MediaTypes::SUPPORTED_MEDIA_TYPES.push("image/webp")
WhatsappSdk::Resource::MediaTypes::SUPPORTED_MEDIA_TYPES.freeze
```
and all worked :)

**Comment by ignacio-chiazzo** [comment]
Hi! Thanks for reporting. We definitely need to add support for `webp` for stickers. 

It's in the Whatsapp documentation too. 

Do you want to open a PR for that? We need:
- [ ] Add `image/webp` to https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/main/lib/whatsapp_sdk/resource/media_types.rb under a new variable `STICKERS_MEDIA`.
- [ ] Add an entry on CHANGELOG.md https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/0cb4187c8530f9d6a85f8dac79f3617434145b43/CHANGELOG.md (you can include your name if you want)

**Comment by renatovico** [comment]
of course i do!
