### ISSUE TITLE
Add Validation For Business Vertical

### ISSUE THREAD

**Issue by renatovico** [ignacio-chiazzo/ruby_whatsapp_sdk#98]
**Is your feature request related to a problem? Please describe.**

Today when business profile is updated, doesn´t have any check if vertical is correct, based on: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/business-profiles/ we can validate if vertical  supplied is correct

**Comment by ignacio-chiazzo** [comment]
Sounds reasonable. Would you like to open a PR with that new validation?

**Comment by renatovico** [comment]
Yep! :)

**Comment by ignacio-chiazzo** [comment]
Added on https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/pull/120. Thanks
